DOC: Add installation instructions for various platforms
TIA-Lab/tiatoolbox pull request #127
Opened 2021-06-17 09:25 UTC by shaneahmed

- Add installation instructions for Windows, Linux and Mac

2021-06-17 16:11 UTC, DavidBAEpstein requested changes

2021-06-17 16:26 UTC, shaneahmed commented on docs/installation.rst
> +and `albumentations` due to compatibility issues.
Good point we should mention that the toolbox is compatible with python 3.6, 3.7 and 3.8

2021-06-17 16:32 UTC, shaneahmed commented on README.md
> +The detailed installation instructions can be found in the [documentation](https://tia-toolbox.readthedocs.io/en/latest/installation.html).
In example taster, the first step takes you to the examples page on Git. The second step follows the first step. I would assume a user is following all the steps and not skipping any.

2021-06-17 16:34 UTC, shaneahmed commented on README.md
> +The detailed installation instructions can be found in the [documentation](https://tia-toolbox.readthedocs.io/en/latest/installation.html).
Addressed in this commit https://github.com/TIA-Lab/tiatoolbox/pull/127/commits/f5968babb1fc21907d9d5c877306b0f8449f2e7a

2021-06-17 16:34 UTC, shaneahmed commented on docs/installation.rst
> +and `albumentations` due to compatibility issues.
Addressed in this commit https://github.com/TIA-Lab/tiatoolbox/pull/127/commits/f5968babb1fc21907d9d5c877306b0f8449f2e7a

2021-06-18 10:49 UTC, John-P commented
It appears that different install methods are being mixed up a little here, which I found confusing. For example, windows says to install openslide with an installer but then openjpeg with conda and then use pip install for the remainder of the packages. On Ubuntu is says to use apt to install openslide and openjpeg, but you can install both of these via conda too (as with openjpeg in the windows section just before). While you can do this, conda recommends that you install everything through conda if you can.

I suggest a structure a bit like this for the instructions:

```
- Briefly outline install methods i.e.: conda, pip (+ system package-manager), docker (maybe, if we make a dockerfile?)
- Windows
  - conda (reccommended / least steps)
  - pip
    - System package prerequisites
- Linux (Ubuntu/Debian)
  - conda (reccommended / least steps)
  - pip
    - System package prerequisites
- macOS
  - conda (reccommended / least steps)
  - pip
    - System package prerequisites
      - homebrew
      - macports
```

Alternatively could do the 'recommended' method for each first then alternative methods in a different section below.

Also, @shaneahmed  I remember discussing that there is this channel which can install openslide for windows, linux and macos (the conda-forge one is linux and mac only). Did we ever test this out? That way we could use one conda file to install everything on each platform.

2021-06-18 11:05 UTC, shaneahmed commented
> It appears that different install methods are being mixed up a little here, which I found confusing. For example, windows says to install openslide with an installer but then openjpeg with conda and then use pip install for the remainder of the packages. On Ubuntu is says to use apt to install openslide and openjpeg, but you can install both of these via conda too (as with openjpeg in the windows section just before). While you can do this, conda recommends that you install everything through conda if you can.
> 
> I suggest a structure a bit like this for the instructions:
> 
> ```
> - Briefly outline install methods i.e.: conda, pip (+ system package-manager), docker (maybe, if we make a dockerfile?)
> - Windows
>   - conda (reccommended / least steps)
>   - pip
>     - System package prerequisites
> - Linux (Ubuntu/Debian)
>   - conda (reccommended / least steps)
>   - pip
>     - System package prerequisites (apt)
> - macOS
>   - conda (reccommended / least steps)
>   - pip
>     - System package prerequisites
>       - homebrew
>       - macports
> ```
> 
> Alternatively could do the 'recommended' method for each first then alternative methods in a different section below.
> 
> Also, @shaneahmed I remember discussing that there is [this channel](https://anaconda.org/sdvillal/openslide) which can install openslide for windows, linux and macos (the conda-forge one is linux and mac only). Did we ever test this out? That way we could use one conda file to install everything on each platform.

There is no openslide channel for Windows on conda as far as I know. The best way is to download the binaries and add to system path.

2021-06-18 12:50 UTC, John-P commented
@shaneahmed 
> There is no openslide channel for Windows on conda as far as I know. The best way is to download the binaries and add to system path.

[This one](https://anaconda.org/sdvillal/openslide) appears to be for windows Mac and Linux. I can give it a test and see if it works when I am next at home (I am in the office right now):
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/4615004/122563347-02e35480-d03c-11eb-81a8-7ab29c8b9c8f.png">

2021-07-01 11:09 UTC, shaneahmed commented on docs/installation.rst
> +1. Download OpenSlide binaries from `this page <https://openslide.org/download/>`_ and add it to
There are several files but we need to add path to openslide directory. I will clarify this.

2021-07-01 11:10 UTC, shaneahmed commented on docs/installation.rst
> +Windows `system path <https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14)>`_.
A directory containing files is added. I will clarify this.

2021-07-01 11:20 UTC, shaneahmed commented on docs/installation.rst
> +If you cannot use Anaconda or are having trouble with it, you can try and alternative install method. Here we will show how to install pre-requisite binary packages before installing pythong dependen
Addressed in this commit https://github.com/TIA-Lab/tiatoolbox/pull/127/commits/288dacaf430cb8637a1a91381c9dc46ad783b9be

2021-07-01 11:20 UTC, shaneahmed commented on docs/installation.rst
> +Windows `system path <https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14)>`_.
Addressed in this commit https://github.com/TIA-Lab/tiatoolbox/pull/127/commits/288dacaf430cb8637a1a91381c9dc46ad783b9be

2021-07-01 11:21 UTC, shaneahmed commented on docs/installation.rst
> +In addition, we remove the packages `datascience` and `albumentations` from Colab because they conflict
Addressed in this commit https://github.com/TIA-Lab/tiatoolbox/pull/127/commits/288dacaf430cb8637a1a91381c9dc46ad783b9be

2021-07-01 11:21 UTC, shaneahmed commented on docs/installation.rst
> +On Linux the preprequiste software can be installed using the command
Addressed in this commit https://github.com/TIA-Lab/tiatoolbox/pull/127/commits/288dacaf430cb8637a1a91381c9dc46ad783b9be

2021-07-02 09:58 UTC, merged