update affiliation in the licence info
TIA-Lab/tiatoolbox pull request #37
Opened 2020-09-22 15:51 UTC by Srijay-lab

Replaced the "2006, Blender Foundation" to "2020, TIALab, University of Warwick" in the licence info.

2020-09-22 17:55 UTC, shaneahmed commented
Thanks @Srijay-lab 
Please can you update files in utils as well?

2020-09-22 17:57 UTC, shaneahmed requested changes
Thanks @Srijay-lab 
Please can you update files in utils as well?

2020-09-23 03:00 UTC, Srijay-lab commented
> Thanks @Srijay-lab
> Please can you update files in utils as well?

2020-09-23 03:02 UTC, Srijay-lab commented
Updated files in utils.

2020-09-23 11:57 UTC, shaneahmed approved these changes

2020-09-23 11:57 UTC, merged